
// A library of base64 encoded sound effects for the game.
// Using data URIs keeps the project self-contained without needing extra asset files.
export const SOUNDS = {
  // UI Sounds
  click: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUYAAABIAIg AEWAgwCIAJgBgCCAJgA/ACgAOgAnADUAJgAwACcAMgAmADMAJwA0ACgANwApADoAKgA8ACsAPgAsAEIALQBFAIwA1QDEAMkA',
  start: 'data:audio/wav;base64,UklGRkYAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUYAAABIAIg AEWAgwCIAJgBgCCAJgA/ACgAOgAnADUAJgAwACcAMgAmADMAJwA0ACgANwApADoAKgA8ACsAPgAsAEIALQBFAIwA1QDEAMkA',
  win: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUEAAAAA/v8EAPz/AgD5/wIA/v8CAPv/BAD+/wIA+v8CAP3/BAD8/wMAAgD9/wQBAAIA+v8IAPn/CwD7/xAA/v8VAQACGBsAIwAoACwALgAvAC4ALQArACgAJwAlACIAIAAdABoAGQAXABU=',
  lose: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUEAAAAAFAARAA0ACAAFAAID/v8CAPz/BAD9/wIA+v8BAPn/AAD4/wAA+P8A+f8BAPsAAvYAB/EAEbYAYbMAKdoB5bsBx+IAy/cA5+QA7doA5+QAzfcA4+IAxbsB2doBXbMAMbYAEcQAA/YAAfsAAPsAAvn/AQD5/wAA+P8A',

  // Battle Sounds
  impact: 'data:audio/wav;base64,UklGRkYAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUYAAACAgICAwMDAv7+/vL29urm5uLa2tLGxsbCwsKmoqKOjo6GhoZ+fn5ycnJubm5eXl5aWlpSUlJGRkZCQkJ+fn52dnZqampmZmZeXl5WVlZSUlJOTk5KSkpKSkpKSkpKSkpKSkpKSkpKSkpISEhISEhISEhISEhISEg==',

  // Dinosaur Roars
  trex_roar: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUQAAACAgICAwMDAv7+/u7u7t7e3srKyq6urpqampaWloqKihISEgYGBfn5+dnZ2c3Nzbm5tbm5ubm5ubm5ubg==',
  raptor_screech: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUQAAADMzMy/v78AAAAAzMzMv7+/AAAAAMzMzL+/vwAAAMzMzL+/vwAAAAA=',
  triceratops_bellow: 'data:audio/wav;base64,UklGRkYAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUYAAACqqqqioqKgoKCbm5uXl5eUlJSQkJCFhYV+fn56enp2dnZxcXFubm5sbGxpaWlpaWlpaWlpaQ==',
  generic_roar: 'data:audio/wav;base64,UklGRkYAAABXQVZFZm10IBAAAAABAAEAiBUAAIgVAAABAAgAZGF0YUYAAACxsbGpqamoqKievr6cnJyampqZmZmXl5eWlpWRkZGOjo6IiIiBgYGAgIB+fn5+fn5+fn5+fg=='
};
